### ISSUE TITLE
Dashboard kWh values don't display if APIKEY is passed 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/dashboard#265] opened 2020-12-08 12:25 UTC
If the read APIKEY is included in the URL but the user is not logged in the rest of the dashboard loads fine. However, the kWh values using the kWh value widget display 0kWh. They only way to make the values display is to make the Feeds public which should not be required if the APIKEY is being passed.

**Comment by chaveiro** [comment] 2022-07-26 22:16
This is by design. A design change would be needed.

**Comment by TrystanLea** [comment] 2022-08-13 19:02
This is now fixed, thanks! 
https://github.com/emoncms/dashboard/commit/d5fedbea32c77684293b35297b45ecafc2668037

**Closed by TrystanLea** 2022-08-13 19:02 UTC
Labels: bug
